language: php

# Add php version so composer doesn't complain
php:
  - 7.1

services:
  - docker

env:
  - DRUPAL_ROOT=/var/www/html

before_script:
  - docker pull statonlab/tripal3

script:
  - docker run -it -d --rm --name tripal -v "$(pwd)":/modules/rawphenotypes statonlab/tripal3
  - sleep 30 # We pause here so postgres and apache complete booting up
  - docker exec -it tripal drush pm-enable -y rawpheno
  - docker exec -it tripal bash -c "cd /modules/rawphenotypes && composer install && DRUPAL_ROOT=/var/www/html ./vendor/bin/phpunit"
